import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';
import Footer from '@/components/footer';
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs';
import { ThemeProvider } from 'next-themes';
import ClerkThemeWrapper from '@/components/ClerkThemeWrapper';

const outfit = Outfit({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-outfit',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html
                lang="en"
                suppressHydrationWarning
                className={`${outfit.className} antialiased`}>
                <body className="bg-[#000008] text-white min-h-screen overflow-auto">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem={false}>
                        <ClerkThemeWrapper>
                            <Nav />
                            <main>{children}</main>
                            <Footer />
                        </ClerkThemeWrapper>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
